package com.lehnade.mbia.memory;

import static org.assertj.core.api.Assertions.assertThat;

import com.drew.imaging.ImageMetadataReader;
import com.drew.metadata.Directory;
import com.drew.metadata.Metadata;
import com.drew.metadata.exif.GpsDirectory;
import com.drew.metadata.file.FileTypeDirectory;
import com.drew.metadata.jfif.JfifDirectory;
import com.drew.metadata.jpeg.HuffmanTablesDirectory;
import com.drew.metadata.jpeg.JpegDirectory;
import com.drew.metadata.xmp.XmpDirectory;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Set;
import java.util.stream.StreamSupport;
import javax.imageio.ImageIO;

/**
 * The committed image fixtures (Phase 3 plan §3.8, generated by
 * {@code backend/scripts/generate-media-fixtures.py}), and what the tests read back from images.
 */
public final class MediaImages {

    /** JPEG 64×32 (red top-left quadrant) with EXIF GPS, orientation 6 and XMP: seen as 32×64. */
    public static final String JPEG_ORIENTATION_6 = "exif-gps-orientation-6.jpg";
    /** PNG 64×32 with EXIF GPS (eXIf) and XMP (iTXt). */
    public static final String PNG_WITH_GPS = "gps.png";
    /** WEBP 64×32 with EXIF GPS and XMP. */
    public static final String WEBP_WITH_GPS = "gps.webp";
    /** Plain text renamed {@code .jpg}. */
    public static final String TEXT_RENAMED_JPG = "text-renamed.jpg";
    /** The bytes of a JPEG, uploaded as a PNG. */
    public static final String JPEG_DECLARED_AS_PNG = "jpeg-declared-as-png.png";
    /** A PNG header announcing 8000×6000 (48 megapixels), with a truncated image stream. */
    public static final String OVER_40_MEGAPIXELS = "over-40-megapixels.png";
    /** JPEG 3000×2000 with EXIF GPS and XMP. */
    public static final String LARGE_WITH_GPS = "large-with-gps-3000x2000.jpg";

    /** The only JPEG structures a derivative may hold: no EXIF, GPS, XMP, IPTC, ICC… */
    private static final Set<Class<? extends Directory>> PIXELS_ONLY = Set.of(JpegDirectory.class,
            JfifDirectory.class, HuffmanTablesDirectory.class, FileTypeDirectory.class);

    private MediaImages() {}

    public static byte[] fixture(String name) {
        try (InputStream input = MediaImages.class.getResourceAsStream("/media/" + name)) {
            assertThat(input).as(name).isNotNull();
            return input.readAllBytes();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    public static BufferedImage decode(byte[] image) {
        try {
            BufferedImage decoded = ImageIO.read(new ByteArrayInputStream(image));
            assertThat(decoded).isNotNull();
            return decoded;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    public static boolean isJpeg(byte[] image) {
        return image.length > 3 && (image[0] & 0xFF) == 0xFF && (image[1] & 0xFF) == 0xD8
                && (image[2] & 0xFF) == 0xFF;
    }

    /** The source really carries a location, in EXIF and in XMP: what must not reach a derivative. */
    public static void assertHasGpsAndXmp(byte[] image) {
        Metadata metadata = metadata(image);
        GpsDirectory gps = metadata.getFirstDirectoryOfType(GpsDirectory.class);
        assertThat(gps).isNotNull();
        assertThat(gps.getGeoLocation()).isNotNull();
        assertThat(metadata.getFirstDirectoryOfType(XmpDirectory.class)).isNotNull();
    }

    /** Read back with metadata-extractor: the image holds no metadata at all, only its pixels. */
    public static void assertHasNoMetadata(byte[] image) {
        List<Class<? extends Directory>> found = StreamSupport
                .stream(metadata(image).getDirectories().spliterator(), false)
                .<Class<? extends Directory>>map(Directory::getClass)
                .toList();
        assertThat(found).isNotEmpty().allMatch(PIXELS_ONLY::contains, "only JPEG structure directories");
        assertThat(new String(image, StandardCharsets.ISO_8859_1))
                .doesNotContain("Exif")
                .doesNotContain("http://ns.adobe.com/xap/1.0/")
                .doesNotContain("xmpmeta")
                .doesNotContain("ICC_PROFILE");
    }

    private static Metadata metadata(byte[] image) {
        try {
            return ImageMetadataReader.readMetadata(new ByteArrayInputStream(image));
        } catch (Exception e) {
            throw new AssertionError("The image metadata cannot be read.", e);
        }
    }
}
